// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20200307174459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Agency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyFareUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agency");
                });

            modelBuilder.Entity("Data.CalendarDates", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("Data.FareAttributes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FareId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transfers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FareAttributes");
                });

            modelBuilder.Entity("Data.FareRules", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContainsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FareId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferDuration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FareRules");
                });

            modelBuilder.Entity("Data.FeedInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeedContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedContactUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedPublisherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedPublisherUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedInfo");
                });

            modelBuilder.Entity("Data.Routes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteLongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteSortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Data.Shapes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContainsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapeDistTraveled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapePtLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapePtLon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapePtSequence")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("Data.StopAmentities", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bench")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BikeRack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shelter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Washroom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StopAmentities");
                });

            modelBuilder.Entity("Data.StopTimes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BikesAllowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropOffType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapeDistTraveled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopSequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timepoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StopTimes");
                });

            modelBuilder.Entity("Data.Stops", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopLon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WheelchairBoarding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("Data.Transfers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExactTimes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinTransferTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Data.Trips", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BikesAllowed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteSortOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WheelchairAccessible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
